### ISSUE TITLE
Unable to compile without CUDA

### ISSUE THREAD

**Issue by jpazurikova** [Fillo7/KTT#14]
Hi,
I am unable to compile KTT, development branch. 
The compilation fails with the message attached here [make.log](https://github.com/Fillo7/KTT/files/1622707/make.log)

First, settings:
- I have Intel OpenCl installed and paths set up
- I DO not have CUDA installed, CUDA_PATH is not set

Second, what I have tried and failed to resolve the situation:
- clean build to rule out some old and obsolete settings in Makefiles
- premake --no-cuda --platform=intel to explicitly tell that I do not have CUDA
- new git clone to rule out the influence of any of my modifications

Master branch works fine, but it does not contain all new features I need to develop a new example.
Happy to answer any additional questions. I hope to see this resolved soon.
Best regards,
Janka

**Comment by Fillo7** [comment]
Thanks for report, should be fixed.

**Comment by jpazurikova** [comment]
Thank you, it's working.
