### ISSUE TITLE
HostZeroCopy not working on OpenCL

### ISSUE THREAD

**Issue by jpazurikova** [Fillo7/KTT#43]
Hi,
I have tried out ArgumentMemoryLocation::HostZeroCopy and came across some unexpected behaviour on OpenCL.

I have a small example showing the issue in https://github.com/jpazurikova/KTT/tree/sort-memory-mapping
There is just one kernel in the composition. Its arguments are initialized with random values, the first several values of the arrays are written on the output. The kernel itself just prints out several of the values from the beginning of the arrays (starts with "beginning"), adds 2 to each value and writes the values again (starts with "end").

CUDA version works as expected, it is clear that the values printed from the kernel are the same than the ones initialized in the host code. I am printing just the first value of uint2, that's why there is only every other value printed out by kernel. Example output:

> 0 128959393 128959393
1 1692901013 1692901013
2 436085873 436085873
3 748533630 748533630
4 776550279 776550279
5 289134331 289134331
6 807385195 807385195
7 556889022 556889022
8 95168426 95168426
9 1888844001 1888844001
[INFO] Initializing tuner for device GeForce GTX 680
[INFO] Computing reference class result for kernel sort
[INFO] Running kernel composition sort with configuration: global size (1, 1, 1), local size (1, 1, 1), parameters: SORT_BLOCK_SIZE: 32, SCAN_BLOCK_SIZE: 32, SORT_VECTOR: 2, SCAN_VECTOR: 2
[DEBUG] Uploading buffer for argument 0, event id: 0
[DEBUG] Performing buffer operation synchronization for event id: 0
[DEBUG] Uploading buffer for argument 1, event id: 1
[DEBUG] Uploading buffer for argument 2, event id: 2
[DEBUG] Uploading buffer for argument 3, event id: 3
[DEBUG] Launching kernel radixSortBlocks, event id: 4
[DEBUG] Performing kernel synchronization for event id: 4
beginning
0  128959393  128959393
1  436085873  436085873
2  776550279  776550279
3  807385195  807385195
4  95168426  95168426
5  1353699824  1353699824
6  686611921  686611921
7  912905316  912905316
8  1698004709  1698004709
9  1532780646  1532780646
end
0  128959395  128959393
1  436085875  436085873
2  776550281  776550279
3  807385197  807385195
4  95168428  95168426
5  1353699826  1353699824
6  686611923  686611921
7  912905318  912905316
8  1698004711  1698004709
9  1532780648  1532780646

However, OpenCL kernel prints out zeros, the initialized values do not "get" to the kernel. Example output:

> 0 128959393 128959393
1 1692901013 1692901013
2 436085873 436085873
3 748533630 748533630
4 776550279 776550279
5 289134331 289134331
6 807385195 807385195
7 556889022 556889022
8 95168426 95168426
9 1888844001 1888844001
[INFO] Initializing tuner for device Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
[INFO] Computing reference class result for kernel sort
[INFO] Running kernel composition sort with configuration: global size (1, 1, 1), local size (1, 1, 1), parameters: SORT_BLOCK_SIZE: 32, SCAN_BLOCK_SIZE: 32, SORT_VECTOR: 2, SCAN_VECTOR: 2
[DEBUG] Uploading buffer for argument 0, event id: 0
[DEBUG] Performing buffer operation synchronization for event id: 0
[DEBUG] Uploading buffer for argument 1, event id: 1
[DEBUG] Uploading buffer for argument 2, event id: 2
[DEBUG] Uploading buffer for argument 3, event id: 3
[DEBUG] Launching kernel radixSortBlocks, event id: 4
[DEBUG]beginning
0  0  0                                                                                                                                                                            
1  0  0
2  0  0
3  0  0
4  0  0
5  0  0
6  0  0
7  0  0
8  0  0
9  0  0
end
0  2  2
1  2  2
2  2  2
3  2  2
4  2  2
5  2  2
6  2  2
7  2  2
8  2  2
9  2  2

This is obviously unexpected behaviour. If KTT does not support HostZeroCopy for OpenCL, it should say so and end the execution. Or fall back and use Device instead of HostZeroCopy.

I have debugged this a little and pinned it down to the following: the bufferEvent for the vectors created at opencl_engine.cpp:279 gets erased in opencl_engine.cpp:525 due to validFlag set to false. The flag set to true causes segfault, so it's probably false for a good reason. You clearly know better what to do, I just wanted to help with finding the origin of the error.

Hope this helps. If you have any questions, just ask.
Janka

**Comment by Fillo7** [comment]
Hi,

HostZeroCopy should work for both backends. The feature was added couple years back and wasn't used that much (none of the examples bundled with KTT use it AFAIK), so it's possible something broke. I'll have a look at it.

**Comment by Fillo7** [comment]
Should be fixed on the development branch.
